### ISSUE TITLE
Update tests to pass for HostGator

### ISSUE THREAD

**Issue by circlecube** [newfold-labs/wp-module-onboarding#325]
This module is integrated with the Hostgator plugin, but only the BR region. Currently the module tests are skipped due to this restriction on region.

We've added a `setRegion` and `setLanguage` command for cypress. See them in use here: `wp-plugin-hostgator/tests/cypress/integration/language.cy.js`

Let's get the onboarding tests updated so they can pass in hostgator. This may take some special care as the tests look like they are expecting english content, so they may need updating to support multi-lingual philosophy. We can check for attributes and that sections exist rather than that the content is in english for example.

**Comment by arunshenoy99** [comment]
Hey @circlecube, does it make sense to implement a matrix for the various regions that the HostGator plugin supports? This way, we can determine the region within the module or the plugin's cypress.config based on the environment and decide to skip tests for all regions except `BR`. This approach would be similar to how we skip Onboarding tests for versions below 6.2 in the BH plugin (see [link](https://github.com/bluehost/bluehost-wordpress-plugin/blob/bb99e1429801c76bac5be4b7931835686d8570e8/cypress.config.js#L51)).

By doing this, we can avoid unnecessary duplication of `setRegion` or `setLanguage` across all our brand plugins, so that tests can locate them and don't error. This will also help keep the code clean and ensure that the module is less concerned with specific regions.

**Comment by circlecube** [comment]
Yes! We have some ideas that we want to implement for testing. Adding brand/region variations to the matrix is a good idea that we hope to do too.

In this, it seems like we'll have hostgator onboarding in place soon, so these tests should be able to pass in either brand. 

The tests will still need some updating so they aren't checking for specific brand-related things or language-related strings, and we can add ids, classes, and or test attributes to elements we need to access in a test. So rather than getting a button with "continue" text, for example, we can select it with something that doesn't change in a different brand/region/language.

**Comment by avneet-raj** [comment]
Hey @circlecube, I've raised the PR (https://github.com/newfold-labs/wp-module-onboarding/pull/419) for the Onboarding Tests to pass across plugins. Since, the Cypress config in the Crazy Domains & HostGator are set to skip tests. So, in this PR, the onboarding tests are not running on HG & CD brand Plugins. Hence, we need to update the config to run these tests.
Thanks!

**Comment by circlecube** [comment]
That's great to hear. I'll update the HostGator and Crazy Domains plugins today so they no longer exclude the onboarding tests.

**Comment by circlecube** [comment]
I've just created a synonymous branch on crazy-domains as well. `add/tests-for-onboarding` so you can update the `plugin-branch` in both the HG and CD sections of the workflow in your branch (until the plugin branches are merged to main) to have the tests run in the plugins. 

There are PRs set up for each plugin here:
 - https://github.com/newfold-labs/wp-plugin-hostgator/pull/413
 - https://github.com/newfold-labs/wp-plugin-crazy-domains/pull/278

And here are the respective branches:
 - https://github.com/newfold-labs/wp-plugin-hostgator/tree/add/tests-for-onboarding
 - https://github.com/newfold-labs/wp-plugin-crazy-domains/tree/add/tests-for-onboarding

Let me know if you've got any questions. Thanks!

**Comment by avneet-raj** [comment]
Hi @circlecube, I've updated the Onboarding PR with the workflow to temporarily update the **plugin-branch** input as **add/tests-for-onboarding** for both CD & HG plugins. While doing so, I found out that on Crazy Domains Plugin, the onboarding Tests are not running because we don't have **uncaught:exception** error handling in index.js configured. So, I updated the PR (https://github.com/newfold-labs/wp-plugin-crazy-domains/pull/278) with this. 

Now, the Tests are passing for all the brand plugins in this PR (https://github.com/newfold-labs/wp-module-onboarding/pull/419).
The tests that are failing are not part of Onboarding Module in HG & CD plugin.

Thanks!

**Comment by circlecube** [comment]
Nice! It will be great having these tests run in each plugin now! 

I've approved the PR you referenced above too. We'll get those other tests fixed in their respective modules.

Thank you!

**Comment by avneet-raj** [comment]
Hi @circlecube, we have tagged a release (https://github.com/newfold-labs/wp-module-onboarding/releases/tag/1.12.1). This includes an Update on Cypress Tests to run across all Brand Plugins (Bluehost, Hostgator & Crazy Domains).

Hence, I'll be closing this issue as this is resolved now.

Thanks!
